language: php

php:
  - '7.2'

sudo: required

dist: trusty

addons:
  chrome: stable

before_install:
  - export APPLITOOLS_BATCH_ID=`echo $TRAVIS_COMMIT`
  - echo $APPLITOOLS_BATCH_ID
  - npm install chromedriver
  - wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
  - java -jar ./selenium-server-standalone-3.141.59.jar &
 
install:
  - composer install
