language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
# Use the faster container based infrastructure.
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "composer install"
  - "curl -s -O http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar"
  - "java -jar selenium-server-standalone-3.4.0.jar &"
