language: php
php:
  - '7.2'
# Use the faster container based infrastructure.
sudo: false
before_install:
  - "export APPLITOOLS_BATCH_ID=`echo $TRAVIS_COMMIT`"
  - "echo $APPLITOOLS_BATCH_ID"
install:
  - "composer install"
