language: php

php:
  - '7.2'

sudo: required

dist: trusty

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
      
before_install:
  - export APPLITOOLS_BATCH_ID=`echo $TRAVIS_COMMIT`
  - echo $APPLITOOLS_BATCH_ID
  - latestChromeDriverURL=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)
  - wget "http://chromedriver.storage.googleapis.com/${latestChromeDriverURL}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip -d /home/travis/build/
  - env webdriver.chrome.driver=/home/travis/build/
  - wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
  - mv ./selenium-server-standalone-3.141.59.jar /home/travis/build/
  - sudo netstat -anp|grep "4444"
  - java -jar /home/travis/build/selenium-server-standalone-3.141.59.jar &
 
install:
  - composer install
